env:
  DISTRIBUTION: zulu
  JDK_CURRENT: 17
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: ${{ env.DISTRIBUTION }}
        java-version: ${{ env.JDK_CURRENT }}
    - continue-on-error: true
      name: Cache Maven dependencies
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B clean install
  deploy:
    if: startsWith(github.ref, 'refs/heads/')
    needs:
    - build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: ${{ env.DISTRIBUTION }}
        java-version: ${{ env.JDK_CURRENT }}
        server-id: sonatype-nexus-snapshots
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      env:
        MAVEN_PASSWORD: ${{ secrets.SONATYPE_PWD }}
        MAVEN_USERNAME: ${{ secrets.SONATYPE_USER }}
      name: Deploy to Sonatype
      run: mvn -B -DskipTests deploy
  doc:
    if: startsWith(github.ref, 'refs/heads/')
    needs:
    - deploy
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: ${{ env.DISTRIBUTION }}
        java-version: ${{ env.JDK_CURRENT }}
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      name: Generate and push doc
      run: chmod -R 777 ./ci/*.sh && ./ci/push-doc-to-gh-pages.sh
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
permissions:
  contents: read
